# Polaris-compatible CDC ACM 1200-baud UF2 bootloader trigger.
CONFIG_RETAINED_MEM=y
CONFIG_RETENTION=y
CONFIG_RETENTION_BOOT_MODE=y
CONFIG_CDC_ACM_DTE_RATE_CALLBACK_SUPPORT=y
CONFIG_ZMK_CDC_ACM_BOOTLOADER_TRIGGER=y
CONFIG_ZMK_CDC_ACM_BOOTLOADER_TRIGGER_DELAY_MS=100
