CONFIG_ZMK_SPLIT=y

CONFIG_ZMK_BLE=y
CONFIG_ZMK_USB=y

CONFIG_ZMK_POINTING=y
CONFIG_INPUT=y
CONFIG_ADC=y
CONFIG_ADC_NRFX_SAADC=y
CONFIG_I2C=y
CONFIG_GPIO=y
CONFIG_SENSOR=y
CONFIG_INPUT_AZOTEQ_IQS5XX=y

CONFIG_SETTINGS=y
CONFIG_NVS=y
CONFIG_FLASH=y
CONFIG_FLASH_PAGE_LAYOUT=y
CONFIG_FLASH_MAP=y
