# Relay left/right key scan diagnostics to the TPS43 Central.
CONFIG_ZMK_KSCAN_DIAGNOSTICS=y
CONFIG_ZMK_KSCAN_DIAGNOSTICS_SPLIT=y
CONFIG_ZMK_SPLIT_RELAY_EVENT=y
CONFIG_ZMK_SPLIT_RELAY_EVENT_DATA_LEN=240
