CONFIG_ZMK_SPLIT=y

CONFIG_ZMK_BLE=y
CONFIG_ZMK_USB=y

CONFIG_ZMK_POINTING=y
CONFIG_INPUT=y
CONFIG_MULTITHREADING=y

CONFIG_ADC=y
CONFIG_ADC_NRFX_SAADC=y
CONFIG_SPI=y
CONFIG_GPIO=y
CONFIG_ADC_ADS1220=y
CONFIG_GPIO_ADS1220=y

CONFIG_INPUT_ANALOG_AXIS_HIRES=y
CONFIG_INPUT_ANALOG_AXIS_HIRES_SETTINGS=y

CONFIG_PM_DEVICE=y
CONFIG_PM_DEVICE_RUNTIME=y

CONFIG_SETTINGS=y
CONFIG_NVS=y
CONFIG_FLASH=y
CONFIG_FLASH_PAGE_LAYOUT=y
CONFIG_FLASH_MAP=y
